path_rf <- file.path("./data" , "UCI HAR Dataset")
files<-list.files(path_rf, recursive=TRUE)
TestActivitydata  <- read.table(file.path(path_rf, "test" , "Y_test.txt" ),header = FALSE)
TrainActivitydata <- read.table(file.path(path_rf, "train", "Y_train.txt"),header = FALSE)
TrainSubjectdata <- read.table(file.path(path_rf, "train", "subject_train.txt"),header = FALSE)
TestSubjectdata  <- read.table(file.path(path_rf, "test" , "subject_test.txt"),header = FALSE)
TestFeaturesdata  <- read.table(file.path(path_rf, "test" , "X_test.txt" ),header = FALSE)
TrainFeaturesdata <- read.table(file.path(path_rf, "train", "X_train.txt"),header = FALSE)
dataSubject <- rbind(TrainSubjectdata, TestSubjectdata)
dataActivity<- rbind(TrainActivitydata,TestActivitydata)
dataFeatures<- rbind(TrainFeaturesdata, TestFeaturesdata)
names(dataSubject)<-c("subject")
names(dataActivity)<- c("activity")
dataFeaturesNames <- read.table(file.path(path_rf, "features.txt"),head=FALSE)
names(dataFeatures)<- dataFeaturesNames$V2
dataCombine <- cbind(dataSubject, dataActivity)
Data <- cbind(dataFeatures, dataCombine)
subdataFeaturesNames<-dataFeaturesNames$V2[grep("mean\\(\\)|std\\(\\)", dataFeaturesNames$V2)]
selectedNames<-c(as.character(subdataFeaturesNames), "subject", "activity" )
Data<-subset(Data,select=selectedNames)
activityLabels <- read.table(file.path(path_rf, "activity_labels.txt"),header = FALSE)
names(Data)<-gsub("^t", "time", names(Data))
names(Data)<-gsub("^f", "frequency", names(Data))
names(Data)<-gsub("Acc", "Accelerometer", names(Data))
names(Data)<-gsub("Gyro", "Gyroscope", names(Data))
names(Data)<-gsub("Mag", "Magnitude", names(Data))
names(Data)<-gsub("BodyBody", "Body", names(Data))
library(plyr);
Data2<-aggregate(. ~subject + activity, Data, mean)
Data2<-Data2[order(Data2$subject,Data2$activity),]
write.table(Data2, file = "tidydata.txt",row.name=FALSE)
